import Head from 'next/head';
import Hero from "../components/Hero/hero";
import Header from "../components/Header/header";
import Plans from "../components/Plans/plans";

export default function Home() {
    return (
        <>
            <Head>
                <title>Health App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Hero />
            <Plans />
        </>
    )
}
